language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 1d970fd2f7da1681cdbd7099267836ed1942d404
  local_dir: dist
  on:
    branch: master
